### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdf in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by sumhncku** [siddharth-agrawal/Neural-Tensor-Network#8]
Hi, 
When I run the neuralTensorNetwork.py file, I have encountered this problem:
I use Python 3.6.

**Traceback (most recent call last):
  File "neuralTensorNetwork.py", line 764, in <module>
    neuralTensorNetwork()
  File "neuralTensorNetwork.py", line 710, in neuralTensorNetwork
    word_indices, num_words = getWordIndices('wordIndices.p')
  File "neuralTensorNetwork.py", line 591, in getWordIndices
    word_dictionary = pickle.load(open(file_name, 'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdf in position 0: ordinal not in range(128)**

Does anyone know how to solve it?

Thanks.

**Comment by NerdTsai** [comment]
python27
